// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dejxqycopsauhhhiwmef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlanhxeWNvcHNhdWhoaGl3bWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjEyODU0NDMsImV4cCI6MjAzNjg2MTQ0M30.ELd_DYidXuYflfCNftFuLCGcXycDUpOxx6vDiibnu6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);